// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.21.12
// source: proxy/internal/rpc/rpcClient/proto/geo.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GeoAddressRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Input string `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
}

func (x *GeoAddressRequest) Reset() {
	*x = GeoAddressRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proxy_internal_rpc_rpcClient_proto_geo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GeoAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeoAddressRequest) ProtoMessage() {}

func (x *GeoAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_internal_rpc_rpcClient_proto_geo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeoAddressRequest.ProtoReflect.Descriptor instead.
func (*GeoAddressRequest) Descriptor() ([]byte, []int) {
	return file_proxy_internal_rpc_rpcClient_proto_geo_proto_rawDescGZIP(), []int{0}
}

func (x *GeoAddressRequest) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

type GeoAddressResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GeoAddressResponse) Reset() {
	*x = GeoAddressResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proxy_internal_rpc_rpcClient_proto_geo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GeoAddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeoAddressResponse) ProtoMessage() {}

func (x *GeoAddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_internal_rpc_rpcClient_proto_geo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeoAddressResponse.ProtoReflect.Descriptor instead.
func (*GeoAddressResponse) Descriptor() ([]byte, []int) {
	return file_proxy_internal_rpc_rpcClient_proto_geo_proto_rawDescGZIP(), []int{1}
}

func (x *GeoAddressResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type GeocodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lat string `protobuf:"bytes,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon string `protobuf:"bytes,2,opt,name=lon,proto3" json:"lon,omitempty"`
}

func (x *GeocodeRequest) Reset() {
	*x = GeocodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proxy_internal_rpc_rpcClient_proto_geo_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GeocodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeocodeRequest) ProtoMessage() {}

func (x *GeocodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_internal_rpc_rpcClient_proto_geo_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeocodeRequest.ProtoReflect.Descriptor instead.
func (*GeocodeRequest) Descriptor() ([]byte, []int) {
	return file_proxy_internal_rpc_rpcClient_proto_geo_proto_rawDescGZIP(), []int{2}
}

func (x *GeocodeRequest) GetLat() string {
	if x != nil {
		return x.Lat
	}
	return ""
}

func (x *GeocodeRequest) GetLon() string {
	if x != nil {
		return x.Lon
	}
	return ""
}

type GeocodeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GeocodeResponse) Reset() {
	*x = GeocodeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proxy_internal_rpc_rpcClient_proto_geo_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GeocodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeocodeResponse) ProtoMessage() {}

func (x *GeocodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_internal_rpc_rpcClient_proto_geo_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeocodeResponse.ProtoReflect.Descriptor instead.
func (*GeocodeResponse) Descriptor() ([]byte, []int) {
	return file_proxy_internal_rpc_rpcClient_proto_geo_proto_rawDescGZIP(), []int{3}
}

func (x *GeocodeResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_proxy_internal_rpc_rpcClient_proto_geo_proto protoreflect.FileDescriptor

var file_proxy_internal_rpc_rpcClient_proto_geo_proto_rawDesc = []byte{
	0x0a, 0x2c, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
	0x2f, 0x72, 0x70, 0x63, 0x2f, 0x72, 0x70, 0x63, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x65, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x29, 0x0a, 0x11, 0x47, 0x65, 0x6f, 0x41, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e,
	0x70, 0x75, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x6e, 0x70, 0x75, 0x74,
	0x22, 0x28, 0x0a, 0x12, 0x47, 0x65, 0x6f, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x34, 0x0a, 0x0e, 0x47, 0x65,
	0x6f, 0x63, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03,
	0x6c, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6c, 0x61, 0x74, 0x12, 0x10,
	0x0a, 0x03, 0x6c, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6c, 0x6f, 0x6e,
	0x22, 0x25, 0x0a, 0x0f, 0x47, 0x65, 0x6f, 0x63, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x32, 0x9d, 0x01, 0x0a, 0x0a, 0x47, 0x65, 0x6f, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x49, 0x0a, 0x10, 0x47, 0x65, 0x6f, 0x41, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x12, 0x18, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x47, 0x65, 0x6f, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x6f,
	0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x44, 0x0a, 0x11, 0x47, 0x65, 0x6f, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x47,
	0x65, 0x6f, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47,
	0x65, 0x6f, 0x63, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x6f, 0x63, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x11, 0x5a, 0x0f, 0x48, 0x55, 0x47, 0x4f, 0x2f,
	0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_proxy_internal_rpc_rpcClient_proto_geo_proto_rawDescOnce sync.Once
	file_proxy_internal_rpc_rpcClient_proto_geo_proto_rawDescData = file_proxy_internal_rpc_rpcClient_proto_geo_proto_rawDesc
)

func file_proxy_internal_rpc_rpcClient_proto_geo_proto_rawDescGZIP() []byte {
	file_proxy_internal_rpc_rpcClient_proto_geo_proto_rawDescOnce.Do(func() {
		file_proxy_internal_rpc_rpcClient_proto_geo_proto_rawDescData = protoimpl.X.CompressGZIP(file_proxy_internal_rpc_rpcClient_proto_geo_proto_rawDescData)
	})
	return file_proxy_internal_rpc_rpcClient_proto_geo_proto_rawDescData
}

var file_proxy_internal_rpc_rpcClient_proto_geo_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proxy_internal_rpc_rpcClient_proto_geo_proto_goTypes = []interface{}{
	(*GeoAddressRequest)(nil),  // 0: proto.GeoAddressRequest
	(*GeoAddressResponse)(nil), // 1: proto.GeoAddressResponse
	(*GeocodeRequest)(nil),     // 2: proto.GeocodeRequest
	(*GeocodeResponse)(nil),    // 3: proto.GeocodeResponse
}
var file_proxy_internal_rpc_rpcClient_proto_geo_proto_depIdxs = []int32{
	0, // 0: proto.GeoService.GeoAddressSearch:input_type -> proto.GeoAddressRequest
	2, // 1: proto.GeoService.GeoAddressGeocode:input_type -> proto.GeocodeRequest
	1, // 2: proto.GeoService.GeoAddressSearch:output_type -> proto.GeoAddressResponse
	3, // 3: proto.GeoService.GeoAddressGeocode:output_type -> proto.GeocodeResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proxy_internal_rpc_rpcClient_proto_geo_proto_init() }
func file_proxy_internal_rpc_rpcClient_proto_geo_proto_init() {
	if File_proxy_internal_rpc_rpcClient_proto_geo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proxy_internal_rpc_rpcClient_proto_geo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GeoAddressRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proxy_internal_rpc_rpcClient_proto_geo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GeoAddressResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proxy_internal_rpc_rpcClient_proto_geo_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GeocodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proxy_internal_rpc_rpcClient_proto_geo_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GeocodeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proxy_internal_rpc_rpcClient_proto_geo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proxy_internal_rpc_rpcClient_proto_geo_proto_goTypes,
		DependencyIndexes: file_proxy_internal_rpc_rpcClient_proto_geo_proto_depIdxs,
		MessageInfos:      file_proxy_internal_rpc_rpcClient_proto_geo_proto_msgTypes,
	}.Build()
	File_proxy_internal_rpc_rpcClient_proto_geo_proto = out.File
	file_proxy_internal_rpc_rpcClient_proto_geo_proto_rawDesc = nil
	file_proxy_internal_rpc_rpcClient_proto_geo_proto_goTypes = nil
	file_proxy_internal_rpc_rpcClient_proto_geo_proto_depIdxs = nil
}
